### ISSUE TITLE
Repo Cert not update

### ISSUE THREAD

**Issue by hyphen1370** [iusrepo/packaging#4] opened 2018-06-04 21:22 UTC
Hello, 

I am not sure this is the right destination for this. 

When I tried to install ius-release rpm. It gives me this error. 

[root@redmine ec2-user]# sudo rpm -i https://centos6.iuscommunity.org/ius-release.rpm
curl: (60) Peer's Certificate issuer is not recognized.
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
error: skipping https://centos6.iuscommunity.org/ius-release.rpm - transfer failed

Could you guys fix this?

Thanks

**Comment by carlwgeorge** [comment] 2018-06-04 21:29
Duplicate of https://github.com/iuscommunity/infrastructure/issues/9.

**Closed as completed by carlwgeorge** 2018-06-04 21:29 UTC
